### ISSUE TITLE
USER STORY Logout

### ISSUE THREAD

**Issue by frirsta** [frirsta/magazine-blog#2]
As a **Site Admin** I can **logout** so that **someone else using my computer can't post from my account**

## Acceptance Criteria
* Acceptance Criteria 1: User can click 'Logout' on every page.

## Tasks
- [ ] Task 1: Add logout url to urls.py.
- [ ] Task 2: Create logout function.
- [ ] Task 3: Import logout function to views.py.
