### ISSUE TITLE
USER STORY Create account

### ISSUE THREAD

**Issue by frirsta** [frirsta/magazine-blog#3]
As a **Site User** I can **create an account** so that **I can comment, like/dislike, and create content for blogposts**

## Acceptance Criteria
* Acceptance Criteria 1: User can click SignUp in the navbar and be redirected to the SignUp page.
* Acceptance Criteria 2: User can give information and sign up.

## Tasks
- [ ] Task 1: Create html file for the user interface.
- [ ] Task 2: Add CSS/Bootstrap.
- [ ] Task 3: Create the Model.
