### ISSUE TITLE
USER STORY View post

### ISSUE THREAD

**Issue by frirsta** [frirsta/magazine-blog#6]
As a **Site User** I can **View posts** so that **I can select one to read**

## Acceptance Criteria
* Acceptance Criteria 1: Article/Text/Image is visible on the blog
* Acceptance Criteria 2: User can see the blog content on the page.

## Tasks
- [ ] Task 1: Create PostList class.
- [ ] Task 2: Create PostDetail class.
- [ ] Task 3: Add path to urlspatterns in blog/urls.py.
- [ ] Task 4: Add path to urlspatterns in magazine/urls.py.
