### ISSUE TITLE
USER STORY Like Post

### ISSUE THREAD

**Issue by frirsta** [frirsta/magazine-blog#9]
As a **Site Admin** I can **Like** so that **I can show that I like a post**

## Acceptance Criteria
* Acceptance Criteria 1: User can click a thumbs up on the blog posts.
* Acceptance Criteria 2: User can see the number of likes.

## Tasks
- [ ] Task 1: Add a thumbs up icon to the post.
- [ ] Task 2:  Create PostLike class.
- [ ] Task 3: Add functions to html file.
